name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        id: snk
        with:
          github_user_name: Nagalakshmi477
          # output path inside the workspace
          outputs: |
            dist/github-contribution-grid-snake.svg
          # optional but sometimes required for org/repos: 
          # github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git add dist || true
          git commit -m "chore: update snake animation" || echo "no changes to commit"

      - name: Publish to 'output' branch (for GitHub Pages)
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
